name: SoshoBird
description: A new Flutter project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  path: ^1.8.3
  sqflite: ^2.0.0
  provider: ^6.1.1
  file_picker: ^4.2.0

  wave: ^0.2.2




  flutter:
    sdk: flutter
  intl: ^0.18.1
  cloud_firestore: ^4.12.2
  firebase_auth: 4.12.1  # Specify an exact version
  firebase_core: 2.21.0   # Specify an exact version
  cupertino_icons: ^1.0.2
  firebase_database: ^10.3.3
  firebase_storage: ^11.4.1




  shared_preferences: ^2.0.10  # Add shared_preferences here
  font_awesome_flutter: ^9.1.0
  flutter_reaction_button: ^3.0.0+2
  visibility_detector: ^0.2.0



  dart_mpesa: ^2.0.3
  video_player: ^2.4.1


  image_picker: ^0.8.1

  flutter_downloader: ^1.11.4
  webview_flutter: ^3.0.0
timeago: ^4.0.1


assets:
  - assets/default_profile_picture.png
  - assets/soshobird.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  provider: ^6.1.1
flutter:
  uses-material-design: true

